#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""转录还原成可粘贴的对话。重点：

  · harness 注入的样板不能当成用户原话——新会话据此推断意图
  · 分级带：用户原话与结论全留，工具调用压成一行，thinking 不留
  · 超限时先丢过程，后丢人话；丢了要明说
  · 深度链接只给真实存在的 scheme，不编造
"""
from __future__ import annotations

import json

import pytest

from agent_handoff.core.transcript import (
    Turn,
    deep_link,
    is_boilerplate,
    merge_tool_runs,
    portable_markdown,
    read_claude_turns,
    read_codex_turns,
    render_markdown,
    resume_command,
    unwrap_injected,
)
from agent_handoff.i18n import Translator


def _write(tmp_path, name, rows):
    fp = tmp_path / name
    fp.write_text(
        "\n".join(json.dumps(r, ensure_ascii=False) for r in rows) + "\n",
        encoding="utf-8",
    )
    return fp


def _claude(role, blocks):
    return {"message": {"role": role, "content": blocks}}


# ── 样板过滤 ──────────────────────────────────────────────────────────

@pytest.mark.parametrize("text", [
    "<local-command-caveat>Caveat: The messages below were generated by...",
    "<command-name>/model</command-name>",
    "<task-notification>done</task-notification>",
    "<recommended_plugins>\nHere is a list...",
    "<system-reminder>be careful</system-reminder>",
    "Caveat: The messages below were generated by the user while running /foo",
    "Base directory for this skill: C:\\x\\y",
    "[Request interrupted by user]",
    "继续",
    "continue",
    "",
    "   ",
])
def test_boilerplate_is_recognised(text):
    """这些都不是人说的话。

    `user` 角色在转录里是个信道而不是一个人：斜杠命令回显、后台任务通知、
    skill 正文、plugin 清单都以它的身份出现。当成用户原话带进新会话，
    等于让新会话从一句样板开始理解整个项目。
    """
    assert is_boilerplate(text)


@pytest.mark.parametrize("text", [
    "接续 agent-handoff-project。仓库在 C:/x，分支 master。",
    "把导出改成分级带，工具调用只留名字",
    "写一段退火算法",
    "在吗",
    "<b>不是</b> harness 标签，只是用户写了 HTML",
])
def test_real_asks_are_kept(text):
    """误杀一条真实诉求比漏掉一条样板严重得多——新会话会不知道用户要什么。"""
    assert not is_boilerplate(text)


def test_tag_with_attributes_is_matched_by_name():
    """按标签名匹配，不是按整串。

    Codex 的 `<codex_internal_context source="goal">` 带属性，写死
    `<codex_internal_context>` 一个都匹配不到——实测这一处漏了 24 次。
    """
    assert is_boilerplate('<turn_aborted reason="x">y</turn_aborted>')


def test_unwrap_keeps_the_goal_inside_the_shell():
    """壳是 harness 加的，里面是用户自己写的目标。整条丢会连目标一起丢。

    所以 `codex_internal_context` **不**在样板名单里——它走剥壳那条路：
    丢掉壳、留下正文，再靠去重压掉「每轮重复注入」的冗余。
    """
    inner = "把导出改成分级带"
    wrapped = f'<codex_internal_context source="goal">{inner}</codex_internal_context>'
    assert not is_boilerplate(wrapped), "带目标的壳不能整条丢"
    assert unwrap_injected(wrapped) == inner


def test_unwrap_handles_nesting_and_empty_shell():
    assert unwrap_injected("<objective><goal>做事</goal></objective>") == "做事"
    assert unwrap_injected("<goal>   </goal>") == ""


def test_repeated_injection_is_deduplicated(tmp_path):
    """同一段目标被每轮重新注入：实测一份 rollout 里重复 24 次。

    逐条留下来会让导出的对话被同一段话刷满，而它只需要说一次。
    """
    goal = '<codex_internal_context source="goal">唯一的目标</codex_internal_context>'
    rows = [
        {"payload": {"type": "message", "role": "user", "text": goal}}
        for _ in range(5
        )
    ]
    rows.append({"payload": {"type": "message", "role": "user", "text": "另一句"}})
    turns = read_codex_turns(_write(tmp_path, "rollout-x.jsonl", rows))
    users = [t.text for t in turns if t.role == "user"]
    assert users == ["唯一的目标", "另一句"]


# ── 分级带 ────────────────────────────────────────────────────────────

def test_thinking_is_not_carried(tmp_path):
    """thinking 无签名不可回放，带过去只是占上下文的中间态文字。"""
    fp = _write(tmp_path, "s.jsonl", [
        _claude("assistant", [
            {"type": "thinking", "thinking": "内部推理不该出现"},
            {"type": "text", "text": "这是结论"},
        ]),
    ])
    turns = read_claude_turns(fp)
    joined = " ".join(t.text for t in turns)
    assert "这是结论" in joined
    assert "内部推理不该出现" not in joined


def test_tool_calls_become_one_line_each(tmp_path):
    """工具调用是过程：占九成体积，而新会话要的是「做过什么」不是每次 grep 的全文。"""
    fp = _write(tmp_path, "s.jsonl", [
        _claude("assistant", [{"type": "tool_use", "id": "t1", "name": "Grep"}]),
        _claude("user", [{
            "type": "tool_result", "tool_use_id": "t1",
            "content": "命中" + "x" * 5000,
        }]),
    ])
    turns = read_claude_turns(fp)
    tools = [x for t in turns for x in t.tools]
    assert any(x.startswith("Grep") for x in turns[0].tools)
    # 结果被压成摘要，不是原文照搬。
    assert all(len(x) < 1200 for x in tools)


def test_merge_tool_runs_collapses_consecutive_rows():
    """一轮里可以有几十次连续工具调用；逐条列出会让读者滚很久才看到人话。"""
    turns = [
        Turn("call", tools=["A"]),
        Turn("call", tools=["B"]),
        Turn("user", "问题"),
        Turn("tool", tools=["r1"]),
        Turn("tool", tools=["r2"]),
    ]
    merged = merge_tool_runs(turns)
    assert [t.role for t in merged] == ["call", "user", "tool"]
    assert merged[0].tools == ["A", "B"]
    assert merged[2].tools == ["r1", "r2"]


# ── 可移植链接 ────────────────────────────────────────────────────────

def test_absolute_path_links_are_downgraded():
    """本机路径链接在别处点不开，而 `file:///C:/Users/<名字>/…` 还泄漏身份。

    判据取自 VSCode 的「复制为 Markdown」：只保留 http/https/mailto 与
    文档内锚点，其余降级成纯文本。
    """
    out = portable_markdown("见 [报告](C:/Users/me/r.md) 与 [文档](https://x.dev)")
    assert "C:/Users/me/r.md" not in out
    assert "https://x.dev" in out
    assert "`报告`" in out


def test_link_definitions_are_dropped():
    """definition 把 target 放在读者看不到的地方，而那往往正是要脱的本机路径。"""
    out = portable_markdown("看 [a][1]\n\n[1]: C:/Users/me/secret.md\n")
    assert "secret.md" not in out


def test_anchor_and_relative_links_survive():
    """`#section` 与相对路径不指名任何机器，换个文档仍然有意义。"""
    out = portable_markdown("[节](#sec) 与 [src](./src/a.py)")
    assert "#sec" in out
    assert "./src/a.py" in out


# ── 续接与深度链接 ────────────────────────────────────────────────────

def test_resume_command_per_agent():
    assert resume_command("Codex", "abc") == "codex resume abc"
    assert resume_command("Claude Code", "abc") == "claude --resume abc"
    assert resume_command("Codex", "") == ""


def test_deep_link_uses_the_session_not_its_parent_thread():
    """深链要指向**这个**会话，不是它 fork 自的那个。

    `thread_id` 是派生来源。让它优先是个真缺陷：Codex 的派生会话里它指向父线程，
    于是三个会话汇总时，第三条的深链指向了第二条的 ID——而卡片上的会话 ID
    显示的是它自己，两者对不上。用户点进去看到的是别人的对话。
    """
    assert deep_link("Codex", "self-id", "parent-thread") == "codex://threads/self-id"
    # 没有 session_id 时才退回 thread_id：那时它是唯一已知的定位信息。
    assert deep_link("Codex", "", "parent-thread") == "codex://threads/parent-thread"


def test_deep_link_only_where_a_scheme_exists():
    """只给真实存在的 scheme。

    Codex 注册了 `codex://threads/<id>`；Claude Code 没有任何 URI scheme。
    编一个不存在的 `claude://…` 会让用户点了没反应，而他无从判断是链接错了
    还是 APP 没装——比不给更糟。
    """
    assert deep_link("Codex", "abc") == "codex://threads/abc"
    assert deep_link("Claude Code", "abc") == ""
    assert deep_link("Codex", "") == ""


# ── 渲染 ──────────────────────────────────────────────────────────────

def test_render_puts_resume_before_the_conversation(tmp_path):
    """原生续接无损，这份 Markdown 有损。先给更好的那条路。"""
    tr = Translator("zh-Hans")
    md = render_markdown(
        "Codex",
        {"session_id": "01a0-x", "cwd": "/w"},
        [Turn("user", "问题"), Turn("assistant", "回答")],
        tr,
    )
    head = md.split("###")[0]
    assert "codex resume 01a0-x" in head
    assert "codex://threads/01a0-x" in head
    assert md.index("codex resume") < md.index("问题")


def test_render_drops_tool_rows_first_and_says_so(tmp_path):
    """超限时先丢过程再丢人话，而且必须明说丢了——静默截断会让读者
    以为看到了全部，然后据此推断「这件事没发生过」。
    """
    tr = Translator("zh-Hans")
    turns = [Turn("user", "目标" * 50)]
    for i in range(40):
        turns.append(Turn("call", tools=[f"tool{i}" + "y" * 200]))
    turns.append(Turn("assistant", "结论" * 50))
    md = render_markdown("Codex", {"session_id": "s"}, turns, tr, max_chars=3000)
    assert len(md) <= 3200
    assert "目标" in md and "结论" in md, "人话要留到最后才截"
    assert "省略" in md or "截断" in md, "丢了东西必须说出来"


def test_truncation_keeps_the_tail_not_just_the_head():
    """截断必须保尾。

    结尾是「上一个会话停在哪」——交接最需要的一句。从头往后切一刀等于把它扔掉，
    新会话于是不知道做到哪了。实测一个 3006 字符的会话被切到 2760 时，
    最后那条结论整条消失。
    """
    tr = Translator("zh-Hans")
    turns = [
        Turn("user", "开头的目标" + "A" * 4000),
        Turn("assistant", "中间的过程" + "B" * 4000),
        Turn("assistant", "结尾的当前进度：卡在第三步"),
    ]
    md = render_markdown("Codex", {"session_id": "s"}, turns, tr, max_chars=2000)
    assert "开头的目标" in md, "头要留"
    assert "结尾的当前进度" in md, "尾更要留——它是交接最需要的一句"


def test_compaction_boundary_is_marked():
    """压缩边界要写出来。

    跨过这条线，之前的原始历史已被摘要取代——新会话据此知道「更早的细节
    不在这份文档里，也不在原会话里了」，而不是以为工具漏抄了。

    `compact` 轮没有正文（Codex 只给 source），所以它不能被空轮过滤吃掉：
    实测漏了这一条时 139 个边界全部消失。
    """
    tr = Translator("zh-Hans")
    turns = [Turn("user", "问"), Turn("compact", "auto"), Turn("assistant", "答")]
    md = render_markdown("Codex", {"session_id": "s"}, turns, tr)
    assert "auto" in md
    assert "压缩" in md


def test_tool_summary_carries_a_count():
    """折叠起来之后读者只看得见 summary 那一行，所以它要带计数。

    「7 次工具调用」比「工具调用」多告诉他这一段有多重。这一点取自
    VSCode 的导出（`Called 5 tools`）。
    """
    tr = Translator("zh-Hans")
    turns = [Turn("call", tools=["Grep", "Read", "Bash"])]
    md = render_markdown("Codex", {"session_id": "s"}, turns, tr)
    assert "<details>" in md and "<summary>" in md
    assert "3" in md.split("</summary>")[0], "summary 里要有数量"
