#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""把一份转录还原成可读、可粘贴的对话。

这是「交接」与「原生续接」之间的中间档：原生续接无损但换不了机器 / 换不了 APP，
而只带压缩摘要的交接又丢得太多。这里把转录里**能带走的全部带走**，
按可复用价值分级。

分级依据是实测的体积分布，不是猜测：
  · 一份 13452 行的 Codex rollout 里，`function_call` 与其输出占 6746 行（50%），
    而真正的对话消息（`message` / `agent_message`）只有 1614 行。
  · 子代理转录的「过程:报告」体积比实测 124:1（14.6 MB 过程 vs 118 KB 报告）。

所以：
  · **用户原话全带** —— 那是意图与约束，最不能丢，也最省地方。
  · **助手结论全带** —— 那是已经得出的判断，重推一遍既费时又可能得出不同结果。
  · **工具调用只留名字与结果摘要** —— 那是过程。占九成体积，而新会话要的是
    「做过什么、结论是什么」，不是每次 grep 的完整输出。
  · **thinking / reasoning 不带** —— 无签名不可回放，带过去只是一堆无法复用的
    中间态文字，白占上下文。

「无损」这件事要说清楚：**做不到。** 模型内部状态与 prompt cache 是服务端加密的，
换会话即失效；被否决方案的推理过程不可回放；工具授权与 MCP 连接是运行时状态。
真正无损的只有原生 `--resume`。这个模块的目标是把有损压到最低，不是消除它。
"""
from __future__ import annotations

import json
import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from ..platform import TranscriptCompressedError, agent_for, open_transcript

# 单条内容的保留长度。用户原话与助手结论给得宽，工具结果给得窄。
#
# 为什么不是同一个数：它们的信息密度差一个数量级。用户说的每一句都可能是约束，
# 而一次 `grep` 的输出里有价值的往往只是「找到了 / 没找到」。
USER_CHARS = 12_000
ASSISTANT_CHARS = 8_000
TOOL_RESULT_CHARS = 400

# 工具调用的**参数**保留长度。
#
# 为什么必须留参数：只留名字等于告诉新会话「上一个会话用过 Edit」，而它真正
# 需要知道的是「上一个会话编辑了哪个文件」。实测一份转录里 `Edit` 出现 43 次，
# 不带参数时这 43 行的信息量合起来等于一行。参数才是「做过什么」里的「什么」。
#
# 给 200 而不是 400：参数里最有价值的是 `file_path`、`pattern`、`command` 这类
# 短字段，而占体积的是 Write / Edit 的整块正文——那些内容已经在磁盘上了，
# 磁盘上的当前状态比转录里的历史版本更可信，没有理由再抄一遍。
TOOL_ARGS_CHARS = 200

# 失败的工具结果保留长度。**故意比成功的宽 5 倍。**
#
# 成功的输出是过程（「找到了」），失败的输出是**下一个会话会重踩的坑**：
# 报错原文里有路径、有行号、有堆栈。原版只数了错误个数从不引用正文，
# 于是新会话拿到「上一个会话有 10 个工具错误」这条毫无行动价值的信息，
# 然后按同样的方式再错一次。
TOOL_ERROR_CHARS = 2_000

# 整份导出的默认上限。超了从**最早的工具摘要**开始丢，保留首尾——
# 开头有目标与约束，结尾有当前进度，中间的过程最可丢。
DEFAULT_MAX_CHARS = 400_000

# 只保留这些 scheme 的链接。绝对路径与其他 scheme 一律降级成纯文本。
#
# 这条判据取自 VSCode 的「复制为 Markdown」：它在导出时把不可移植的本机路径
# 链接降级成纯文本，并删掉 link definition——因为那里藏着读者没看见的绝对路径。
# 同一个道理适用于这里：导出的 md 是要粘到别处、给别人看的，
# `file:///C:/Users/<名字>/…` 既没用又泄漏身份。
_PORTABLE_SCHEME = re.compile(r"^(?:https?|mailto):", re.I)
_ABS_PATH = re.compile(r"^(?:[A-Za-z]:[\\/]|[\\/]{1,2}[^\\/])")
_MD_LINK = re.compile(r"(!?)\[([^\]]*)\]\(([^)]+)\)")
# 行首的 link definition（`[label]: target`）。读者从没看见这个 target，
# 留着等于把它单独发布出去。
_MD_DEF = re.compile(r"^[ \t]{0,3}\[[^\]]+\]:[ \t]*\S+.*$", re.M)

# harness 注入到 user 轮里的样板。**这些不是用户说的话。**
#
# 为什么必须挡：`user` 角色在转录里是个信道，不是一个人。斜杠命令回显、
# 后台任务通知、skill 正文、plugin 清单、系统提醒全都以 user 身份出现。
# 实测一份转录的 user 轮里 `<command-name>` 出现 28 次、`<task-notification>`
# 14 次，而真实诉求只有 23 条。不挡的后果是导出的「用户原话」开头是
# `<local-command-caveat>Caveat: The messages below were generated by...`——
# 新会话据此推断意图，等于从一句样板开始理解整个项目。
#
# 按**标签名**匹配而不是整串：Codex 的 `<codex_internal_context source="goal">`
# 带属性，写死 `<codex_internal_context>` 一个都匹配不到。实测这一处漏了 24 次。
_BOILERPLATE_TAGS = frozenset({
    "local-command-caveat", "command-name", "command-message", "command-args",
    "local-command-stdout", "local-command-stderr", "system-reminder",
    "task-notification", "subagent_notification", "recommended_plugins",
    "environment_context", "user-prompt-submit-hook", "post-tool-use-hook",
    "pre-tool-use-hook", "session-start-hook", "ide_selection",
    "ide-opened-file", "cross-session-message", "turn_aborted",
    "session_knowledge", "persisted-output",
})
_BOILERPLATE_HEAD = (
    "caveat: the messages below were generated by the user while running",
    "base directory for this skill:",
)
# 剥壳保内容的标签：壳是 harness 加的，里面是用户自己设的目标。
#
# 整条丢掉会连目标一起丢——那正是新会话最需要知道的东西。所以剥掉壳、
# 留下正文，再靠去重压掉「每轮重复注入」带来的冗余。
_UNWRAP_TAGS = frozenset({"codex_internal_context", "objective", "goal"})
_TAG_HEAD = re.compile(r"^<([A-Za-z][\w.:-]*)(\s[^>]*)?>")

# 整条就是这些的，是状态标记而不是诉求。
_BOILERPLATE_EXACT = (
    "[request interrupted by user]",
    "[request interrupted by user for tool use]",
    "no response requested.",
    "continue from where you left off.",
    "continue",
    "继续",
)


def unwrap_injected(text: str) -> str:
    """剥掉 harness 包在用户诉求外面的壳，保留里面的正文。

    只处理 `_UNWRAP_TAGS`：那些壳里装的是用户自己写的目标。其余标签由
    `is_boilerplate` 整条挡掉。
    """
    t = text.strip()
    while True:
        m = _TAG_HEAD.match(t)
        if not m or m.group(1).lower() not in _UNWRAP_TAGS:
            return t
        close = f"</{m.group(1)}>"
        end = t.rfind(close)
        inner = t[m.end():end] if end > 0 else t[m.end():]
        stripped = inner.strip()
        if not stripped:
            return ""
        t = stripped


# 助手发言里内嵌的推理块。Codex 会把 `<thinking>…</thinking>` 直接拼在
# `agent_message` 的正文里，所以「不取 reasoning 类型」挡不住它——实测导出的
# Markdown 里仍有 10 处泄漏。
#
# 为什么必须剥：thinking 无签名不可回放，带过去只是一堆无法复用的中间态文字，
# 白占新会话的上下文；而它常常包含「先试 A 再试 B」这类已被放弃的路线，
# 新会话照着读会重走弯路。
_THINKING_BLOCK = re.compile(r"<thinking>.*?</thinking>", re.S | re.I)
_THINKING_OPEN = re.compile(r"<thinking>.*\Z", re.S | re.I)


def strip_thinking(text: str) -> str:
    """剥掉正文里内嵌的 thinking 块，返回剩下的结论。

    没有闭合标签的（流式中断留下的半截）也要剥：留着会把后面所有内容都
    当成推理的一部分显示出去。
    """
    out = _THINKING_BLOCK.sub("", text or "")
    out = _THINKING_OPEN.sub("", out)
    return out.strip()


def is_boilerplate(text: str) -> bool:
    """这条 user 轮是 harness 注入的，还是人真的说了话？

    只看开头与整条相等两种形态，不做模糊判断：漏掉一条样板只是多几行噪声，
    误杀一条真实诉求会让新会话不知道用户要什么——后者严重得多。
    """
    t = text.strip()
    if not t:
        return True
    low = t.lower()
    if low in _BOILERPLATE_EXACT:
        return True
    if any(low.startswith(h) for h in _BOILERPLATE_HEAD):
        return True
    m = _TAG_HEAD.match(t)
    return bool(m and m.group(1).lower() in _BOILERPLATE_TAGS)


@dataclass
class Turn:
    """一轮对话里被保留下来的东西。"""

    role: str
    text: str = ""
    tools: list[str] = field(default_factory=list)

    def is_empty(self) -> bool:
        """这一轮有没有东西可写？

        `compact` 是**事件**而不是发言：它本身没有正文（Codex 只给出 source），
        但「此处压缩过」这件事恰恰是要留下的信息。所以它永不为空——
        否则渲染循环开头的空轮过滤会把 139 个压缩边界全部吃掉（实测如此）。
        """
        if self.role == "compact":
            return False
        return not self.text.strip() and not self.tools


def portable_markdown(text: str) -> str:
    """把 Markdown 里不可移植的链接降级成纯文本。

    保留 http/https/mailto 与文档内锚点（`#section` 不指向任何机器，
    换个文档仍然有意义）；绝对路径、`file://`、其他 scheme 一律只留标签文字。

    删掉 link definition：它把 target 放在读者看不到的地方，
    而那个 target 往往正是要脱掉的本机路径。
    """
    def keep(target: str) -> bool:
        t = target.strip()
        if not t:
            return False
        if _PORTABLE_SCHEME.match(t):
            return True
        # 文档内锚点与相对路径不指名任何机器。
        return not _ABS_PATH.match(t) and not re.match(r"^[a-z][a-z0-9.+-]*:", t, re.I)

    def sub(m: re.Match[str]) -> str:
        # 第 1 组是图片的 `!`。目标被剥掉之后图片和链接的下场一样——
        # 都只剩读者看到的那段文字，所以这里不需要区分。
        label, target = m.group(2), m.group(3)
        if keep(target):
            return m.group(0)
        # 只留读者看到的文字，用行内代码标出来——它曾经是个链接，
        # 现在只是个名字，加上反引号避免读者以为它还能点。
        return f"`{label}`" if label.strip() else ""

    out = _MD_LINK.sub(sub, text)
    return _MD_DEF.sub("", out)


def _clip(text: str, limit: int) -> str:
    """超长就截断并明说截了多少，不静默丢。

    静默截断的后果是读者以为看到了全部，然后据此推断「这件事没发生过」。
    把丢掉的量写出来，读者才知道要不要去看原始转录。
    """
    s = (text or "").strip()
    if len(s) <= limit:
        return s
    return s[:limit] + f"\n\n[... 截断 {len(s) - limit} 字符，完整内容见转录原文]"


def _text_from_blocks(content: Any, want: set[str]) -> str:
    """从 content 里取出想要的块类型，拼成文本。"""
    if isinstance(content, str):
        return content
    if not isinstance(content, list):
        return ""
    parts: list[str] = []
    for b in content:
        if not isinstance(b, dict):
            continue
        if b.get("type") in want:
            val = b.get("text") or b.get("content") or ""
            if isinstance(val, str) and val.strip():
                parts.append(val)
    return "\n\n".join(parts)


def _tool_line(name: str, result: str, args: str = "", failed: bool = False) -> str:
    """一次工具调用压成一行：名字 + 参数 + 结果摘要。

    参数为什么在结果前面：读者扫这一行时先要知道「对什么做的」，再看「结果如何」。
    `Edit -> ok` 什么都没说；`Edit(src/core/plan.py) -> ok` 才是一条事实。

    `failed` 为真时结果给 `TOOL_ERROR_CHARS` 的额度而不是 `TOOL_RESULT_CHARS`：
    失败的原文是下一个会话会重踩的坑，成功的输出只是过程。
    """
    name = (name or "?").strip()[:80]
    limit = TOOL_ERROR_CHARS if failed else TOOL_RESULT_CHARS
    brief = " ".join((result or "").split())[:limit]
    head = f"{name}({args})" if args else name
    if not brief:
        return head
    # 失败要一眼看出来。不靠颜色（Markdown 里没有），靠一个词。
    return f"{head} !! {brief}" if failed else f"{head} -> {brief}"


def _tool_args(raw: Any) -> str:
    """把工具入参压成一行可读的摘要。

    只取标量字段，且**按信息价值排序**而不是按 dict 顺序：`file_path` 与
    `command` 是「对什么做的」，而 `content`、`new_string` 这类整块正文占掉
    全部额度却几乎没有交接价值——它们改出来的结果已经在磁盘上了，磁盘上的
    当前状态比转录里的历史版本更可信。

    不做 JSON dump：`{"file_path": "a.py", "old_string": "..."}` 里的引号与
    大括号会占掉三成额度，而读者要的只是那几个值。
    """
    if isinstance(raw, str):
        return " ".join(raw.split())[:TOOL_ARGS_CHARS]
    if not isinstance(raw, dict):
        return ""
    # 前面的先进。命中的键在不同 APP、不同工具里叫法不一，所以列得宽一些。
    _PREFERRED = (
        "file_path", "path", "notebook_path", "command", "pattern", "query",
        "url", "glob", "cmd", "expression", "language", "subagent_type",
        "skill", "description", "prompt",
    )
    parts: list[str] = []
    used: set[str] = set()

    def push(key: str, val: Any) -> None:
        if key in used:
            return
        if not isinstance(val, (str, int, float, bool)):
            return
        text = " ".join(str(val).split())
        if not text:
            return
        used.add(key)
        # 单个值也要有上限：一条 300 字符的 `command` 会把整行额度吃光，
        # 后面的 `file_path` 就进不来了。
        parts.append(f"{key}={text[:120]}")

    for key in _PREFERRED:
        if key in raw:
            push(key, raw[key])
    for key, val in raw.items():
        if len(", ".join(parts)) >= TOOL_ARGS_CHARS:
            break
        push(str(key), val)
    out = ", ".join(parts)
    return out[:TOOL_ARGS_CHARS]


def _is_error_result(block: dict, text: str) -> bool:
    """这条工具结果是失败的吗？

    优先信结构化标记（Claude 的 `is_error`），它是 APP 自己下的判断。没有标记时
    才看正文开头——**只看开头**：正文里出现 "error" 三个字母的成功输出太多了
    （grep 结果、日志摘录、代码里的错误处理分支），在整段里搜等于把大半成功
    结果误判成失败，然后给它们 5 倍额度，把文档撑爆。
    """
    for key in ("is_error", "isError"):
        val = block.get(key)
        if isinstance(val, bool):
            return val
    head = " ".join((text or "").split())[:160].lower()
    return head.startswith((
        "error", "error:", "traceback", "exception", "fatal",
        "permission denied", "command failed", "no such file",
        "einval", "enoent", "eacces",
    ))


def read_claude_turns(fp: Path) -> list[Turn]:
    """读 Claude Code 的转录。

    结构：每行一个 JSON，`message.role` 是 user/assistant，
    `message.content` 是块数组（`text` / `thinking` / `tool_use` / `tool_result`）。
    实测一份 27 行的转录里有 thinking 4、tool_use 6、tool_result 6、text 1。
    """
    turns: list[Turn] = []
    # tool_use_id -> (工具名, 参数摘要)。参数要跟着 id 走：调用与结果分在两条
    # 记录里（assistant 发 tool_use，下一条 user 带 tool_result），只有靠 id
    # 才能把「对什么做的」与「结果如何」拼回同一行。
    pending: dict[str, tuple[str, str]] = {}
    # 已出现过的用户原话。harness 会把同一个目标每轮重新注入一次——实测一份
    # 转录里同一段 `<codex_internal_context source="goal">` 出现 24 次。
    # 逐条留下来会让导出的对话被同一段话刷满，而它只需要说一次。
    seen_user: set[str] = set()
    for line in _lines(fp):
        obj = _loads(line)
        if obj is None:
            continue
        msg = obj.get("message")
        if not isinstance(msg, dict):
            continue
        role = msg.get("role")
        content = msg.get("content")

        if role == "user":
            # user 消息里可能混着 tool_result（那是上一轮工具的回执，不是人说的话）。
            said = _text_from_blocks(content, {"text"})
            if isinstance(content, str):
                said = content
            results: list[str] = []
            if isinstance(content, list):
                for b in content:
                    if isinstance(b, dict) and b.get("type") == "tool_result":
                        name, args = pending.pop(str(b.get("tool_use_id") or ""), ("tool", ""))
                        raw = b.get("content")
                        if isinstance(raw, list):
                            raw = _text_from_blocks(raw, {"text"})
                        text = str(raw or "")
                        results.append(
                            _tool_line(name, text, args, failed=_is_error_result(b, text))
                        )
            # 样板轮丢掉：`user` 角色在转录里是个信道而不是一个人，斜杠命令回显、
            # 后台任务通知、plugin 清单都以它的身份出现。实测不挡的话，导出的
            # 第一条「用户原话」会是 `<local-command-caveat>Caveat: ...`。
            if said.strip() and not is_boilerplate(said):
                said = unwrap_injected(said)
                if said and said not in seen_user:
                    seen_user.add(said)
                    turns.append(Turn("user", _clip(said, USER_CHARS)))
            if results:
                turns.append(Turn("tool", tools=results))
        elif role == "assistant":
            # thinking 刻意不取：无签名不可回放，带过去只占地方。
            said = _text_from_blocks(content, {"text"})
            calls: list[str] = []
            if isinstance(content, list):
                for b in content:
                    if isinstance(b, dict) and b.get("type") == "tool_use":
                        nm = str(b.get("name") or "tool")
                        args = _tool_args(b.get("input"))
                        pending[str(b.get("id") or "")] = (nm, args)
                        calls.append(f"{nm}({args})" if args else nm)
            # Claude 的 thinking 是独立 block（上面已经不取），但正文里也可能
            # 内嵌 `<thinking>` 标签，所以这里同样剥一遍。
            said = strip_thinking(said)
            if said:
                turns.append(Turn("assistant", _clip(said, ASSISTANT_CHARS)))
            if calls:
                turns.append(Turn("call", tools=calls))
    return turns


def read_codex_turns(fp: Path) -> list[Turn]:
    """读 Codex 的 rollout。

    结构：每行 `{"type": ..., "payload": {...}}`。实测 payload.type 的分布里
    `function_call` + `function_call_output` 占一半，`message`/`agent_message`
    才是对话本体，`reasoning`/`agent_reasoning` 是不可回放的中间态。
    """
    turns: list[Turn] = []
    # call_id -> (工具名, 参数摘要)。与 Claude 侧同理：`function_call_output`
    # 记录里没有工具名，只有 call_id。
    pending: dict[str, tuple[str, str]] = {}
    # 同一段目标被每轮重新注入：实测一份 rollout 里重复 24 次。
    seen_user: set[str] = set()
    # 助手发言的去重。**Codex 把同一条发言同时写进 `message` 与 `agent_message`
    # 两种 payload**——实测一份 rollout 里 message 1028 条、agent_message 807 条，
    # 而导出后 `**助手：**` 出现 737 次、实际内容只有约 368 条，每条整整重复一次。
    # 不去重的后果是导出体积翻倍，而新会话读到同一段叙述两遍，会以为那是两次
    # 独立的判断。
    seen_asst: set[tuple[int, int]] = set()

    def take_assistant(text: str) -> None:
        """收一条助手发言，重复的丢掉。"""
        body = strip_thinking(text)
        if not body:
            return
        # 去重键必须覆盖整条正文，不能只取开头。
        #
        # 原版取前 400 个归一化字符。Codex 的双写确实是**逐字**重复，400 字符
        # 足够识别；但代价是**开头相同的不同长消息会被静默丢掉**——而助手发言
        # 恰恰常以同一句话起头（「好的，我先看一下…」「已完成。」后面接完全
        # 不同的内容）。丢掉的是结论，而结论是这份文档最不能丢的东西。
        #
        # 用长度 + 完整正文的哈希：逐字重复照样命中，开头相同但内容不同的
        # 一定不命中。哈希而不是存原文，是因为 seen 集合要跟着整份转录走，
        # 存原文等于把所有助手发言在内存里留两份。
        norm = " ".join(body.split())
        key = (len(norm), hash(norm))
        if key in seen_asst:
            return
        seen_asst.add(key)
        turns.append(Turn("assistant", _clip(body, ASSISTANT_CHARS)))

    for line in _lines(fp):
        obj = _loads(line)
        if obj is None:
            continue
        pl = obj.get("payload")
        if not isinstance(pl, dict):
            continue
        ptype = pl.get("type")

        if ptype == "message":
            role = pl.get("role")
            said = _text_from_blocks(pl.get("content"), {"text", "input_text", "output_text"})
            if not said:
                said = str(pl.get("text") or "")
            if not said.strip():
                continue
            if role == "user":
                # Codex 侧同样要挡 harness 样板：实测导出的首条「用户原话」
                # 是 `<recommended_plugins>`，那是插件清单而不是诉求。
                if not is_boilerplate(said):
                    said = unwrap_injected(said)
                    if said and said not in seen_user:
                        seen_user.add(said)
                        turns.append(Turn("user", _clip(said, USER_CHARS)))
            elif role == "assistant":
                take_assistant(said)
            # developer 角色是系统注入的指令，不是人说的话，也不是助手的结论。
        elif ptype == "agent_message":
            take_assistant(str(pl.get("message") or pl.get("text") or ""))
        elif ptype in ("context_compacted", "compacted"):
            # 压缩边界要标出来。跨过这条线，之前的原始历史已经被摘要取代——
            # 新会话据此就知道「更早的细节不在这份文档里，也不在原会话里了」，
            # 而不是以为工具漏抄了。VSCode 的导出里同样有这个标记。
            src = str(pl.get("source") or pl.get("reason") or "").strip()
            turns.append(Turn("compact", text=src))
        elif ptype in ("function_call", "custom_tool_call", "mcp_tool_call_begin"):
            nm = _codex_tool_name(pl)
            args = _tool_args(pl.get("arguments") or pl.get("input") or pl.get("args"))
            # 名字要记住：`function_call_output` 那条记录里**没有**工具名，
            # 原版因此把结果一律写成 `output`，MCP 工具名整个丢掉。Codex 的
            # call 与 output 靠 `call_id` 配对，跟 Claude 的 tool_use_id 同理。
            call_id = str(pl.get("call_id") or pl.get("id") or "")
            if call_id:
                pending[call_id] = (nm, args)
            turns.append(Turn("call", tools=[f"{nm}({args})" if args else nm]))
        elif ptype in ("function_call_output", "mcp_tool_call_end"):
            out = pl.get("output")
            if isinstance(out, dict):
                # 失败标记也在这一层。取正文之前先记下来，取完就没了。
                out_err = out.get("success") is False or bool(out.get("is_error"))
                out = out.get("content") or out.get("text") or out.get("output") or ""
            else:
                out_err = False
            text = str(out or "")
            call_id = str(pl.get("call_id") or pl.get("id") or "")
            name, args = pending.pop(call_id, ("", ""))
            if not name:
                # 配不上对（call 记录缺失、或者 id 字段换过名字）时仍然要有个
                # 名字。写 `output` 是原版的做法，至少别把它当成真实工具名。
                name = "output"
            failed = out_err or _is_error_result(pl, text)
            turns.append(Turn("tool", tools=[_tool_line(name, text, args, failed=failed)]))
    return turns


def _codex_tool_name(pl: dict) -> str:
    """从一条 Codex 调用记录里取出工具名。

    四种写法都见过：`name`（function_call）、`tool`（custom_tool_call）、
    以及 MCP 的 `server` + `tool` 两段式。MCP 那种要拼起来——只留 `tool`
    会让两个服务器上同名的工具在文档里无法区分。
    """
    server = str(pl.get("server") or "").strip()
    tool = str(pl.get("tool") or pl.get("name") or "").strip()
    if server and tool:
        return f"{server}/{tool}"[:80]
    return (tool or "tool")[:80]


def _lines(fp: Path):
    """逐行读，坏字节不致命。

    转录可能被别的进程正在写、可能有非 UTF-8 字节。`errors="replace"` 让一份
    半损的转录仍然能导出大部分内容——比整个失败有用。

    压缩转录（Codex 7 天后自动生成的 `.jsonl.zst`）走同一条路径：
    `open_transcript` 按扩展名挑解压流。本机没有 zstd 实现时它抛
    `TranscriptCompressedError`，这里当作「读不到内容」处理——渲染方拿到空的
    轮次列表，会照它自己的空态逻辑提示，而不是崩掉。
    """
    try:
        with open_transcript(fp) as fh:
            for line in fh:
                s = line.strip()
                if s:
                    yield s
    except (OSError, TranscriptCompressedError):
        return
    except Exception:
        # zstd 流损坏（截断、校验失败）与 OSError 同等对待：能读多少算多少。
        return


def _loads(line: str) -> dict[str, Any] | None:
    try:
        obj = json.loads(line)
    except (json.JSONDecodeError, ValueError):
        return None
    return obj if isinstance(obj, dict) else None


def read_turns(agent: str, fp: Path) -> list[Turn]:
    """按 agent 选解析器。认不出就两个都试——格式判断错不该让导出变成空文件。

    调用方给的 `agent` 优先；为空时用 `platform.agent_for` 从路径判定，
    与其余各处同一份判据。

    路径判定能覆盖调用方的说法：调用方可能只是从别处透传了一个默认值，
    而文件名前缀（`rollout-`）是 Codex 自己的命名契约，比传参可靠。
    """
    if "Codex" in (agent, agent_for(fp)):
        turns = read_codex_turns(fp)
        return turns or read_claude_turns(fp)
    turns = read_claude_turns(fp)
    return turns or read_codex_turns(fp)


def merge_tool_runs(turns: list[Turn]) -> list[Turn]:
    """把连续的工具轮合并，避免一行一个 `call` 刷满整份文档。

    实测一轮里可以有几十次连续工具调用；逐条列出会让读者滚很久才看到下一句
    人话，而那些行的信息量加起来不如一句「查了这些东西」。
    """
    out: list[Turn] = []
    for t in turns:
        if t.role in ("call", "tool") and out and out[-1].role == t.role:
            out[-1].tools.extend(t.tools)
        else:
            out.append(Turn(t.role, t.text, list(t.tools)))
    return out


def resume_command(agent: str, session_id: str) -> str:
    """原生续接命令。**这是首选路径，交接是退路。**

    先给这一条，因为它无损：官方文档写的是恢复 full history including tool calls
    and results，即原样重放 token。下面那份 Markdown 是有损摘要，只在原生续接
    做不到时才用（换机器、换 APP、上下文已满、转录损坏）。

    命令形态照官方写法，不自己编：
      · Claude Code：`claude --resume <session-id>`
      · Codex：`codex resume <id>`
    """
    sid = (session_id or "").strip()
    if not sid:
        return ""
    if agent == "Codex":
        return f"codex resume {sid}"
    return f"claude --resume {sid}"


def deep_link(agent: str, session_id: str, thread_id: str = "") -> str:
    """能直接唤起 APP 的深度链接，没有就返回空串。

    只给真实存在的 scheme。Codex 注册了 `codex://threads/<id>`（在它自己的
    桌面端集成代码里就是这么拼的）；Claude Code 没有任何 URI scheme，
    所以这里返回空串，由调用方改用 resume 命令。

    编一个不存在的 scheme 比不给更糟：用户点了没反应，且无从判断是链接错了
    还是 APP 没装。

    **`session_id` 优先，`thread_id` 只作兜底。** 反过来写是个真缺陷：
    `thread_id` 是**派生来源**（这个会话从哪个线程 fork 出来的），不是本会话
    的身份。Codex 的派生会话里它指向父线程，于是链接会跳到另一个会话——
    实测三个会话汇总时，第三条的深链指向了第二条的 ID，而卡片上的会话 ID
    显示的是它自己，两者对不上。用户点进去看到的是别人的对话。
    """
    sid = (session_id or thread_id or "").strip()
    if not sid:
        return ""
    if agent == "Codex":
        return f"codex://threads/{sid}"
    return ""


def render_markdown(
    agent: str,
    meta: dict[str, Any],
    turns: list[Turn],
    tr: Any,
    max_chars: int = DEFAULT_MAX_CHARS,
) -> str:
    """把一个会话渲染成可直接粘给新会话的 Markdown。

    分级带（不是全带，也不是只带摘要）：
      · 用户原话与助手结论按原文进，只做长度上限截断
      · 工具调用压成一行「名字 -> 结果摘要」
      · thinking / reasoning 不进

    超限时**先丢工具行**，因为它们是过程；人话最后才截。这个顺序保证了
    「装不下」的时候丢掉的是最不需要的部分，而不是从中间一刀切。

    所有文本过 `_redact`：这份 md 是要拷到别处、可能被提交、可能发给别人的，
    而会话原文里有本机路径、用户名、粘过的密钥。
    """
    from .report import _redact

    nl = "\n"
    head: list[str] = []
    a = head.append
    a(f"## {agent} · {meta.get('session_id', '')[:8] or '?'}")
    a("")
    resume = resume_command(agent, str(meta.get("session_id") or ""))
    if resume:
        a("- " + tr.t("md.resume", cmd=resume))
    link = deep_link(agent, str(meta.get("session_id") or ""), str(meta.get("thread_id") or ""))
    if link:
        a("- " + tr.t("md.deeplink", url=link))
    for tkey, key in (
        ("md.field.session_id", "session_id"),
        ("md.field.cwd", "cwd"),
        ("md.field.title", "title"),
        ("md.field.mtime", "mtime"),
    ):
        val = str(meta.get(key) or "").strip()
        if val:
            a("- " + tr.t(tkey, value=_redact(val)))
    a("")
    a("### " + tr.t("md.conversation"))
    a("")

    body: list[str] = []
    tool_idx: list[int] = []
    for t in turns:
        if t.is_empty():
            continue
        if t.role == "user":
            body.append(tr.t("md.speaker.user") + nl + nl + portable_markdown(_redact(t.text)))
        elif t.role == "assistant":
            body.append(tr.t("md.speaker.assistant") + nl + nl + portable_markdown(_redact(t.text)))
        elif t.role == "compact":
            # 压缩边界。它不是一句发言，而是一条「此处之前的历史已被摘要取代」
            # 的事实——读者据此知道更早的细节不在这份文档里，也不在原会话里了。
            body.append("> " + tr.t("md.compacted", source=t.text or "auto"))
        else:
            tool_idx.append(len(body))
            lines = nl.join(f"- `{_redact(x)}`" for x in t.tools)
            # summary 上带计数：折叠起来之后读者只看得见这一行，
            # 「7 次工具调用」比「工具调用」多告诉他这一段有多重。
            # 这一点取自 VSCode 的导出（`Called 5 tools`）。
            label = tr.t("md.tools_n", count=len(t.tools))
            body.append(
                f"<details><summary>{label}</summary>"
                + nl + nl + lines + nl + nl + "</details>"
            )
        body.append("")

    def joined() -> str:
        parts = head + [x for x in body if x is not None]
        return nl.join(parts).rstrip() + nl

    # 超限：从最早的工具块开始丢（最老的过程最不需要）。
    #
    # 不能每丢一个就 `joined()` 重算一次全文。那是 O(工具块数 × 全文长度)——
    # 实测一份 rollout 里 function_call 与其输出占 6746 行，合并后仍有几百个
    # 工具块，而全文几十万字符：一次导出要重建全文几百遍。这是这个模块最大
    # 的耗时点，且转录越大越糟。
    #
    # 改成按长度记账：先算出总长，再逐个减去要丢的块长度（外加它自己那个
    # 换行符）。只有确定要丢哪些之后才拼一次。
    per = [0 if x is None else len(x) for x in body]
    total = len(nl.join(head)) + sum(per) + len(body) + 1  # 每块后一个 nl，末尾一个
    dropped = 0
    for i in tool_idx:
        if total <= max_chars:
            break
        if body[i] is not None:
            total -= per[i] + len(nl)
            body[i] = None
            dropped += 1
    out = joined()
    if dropped:
        out += nl + "> " + tr.t("md.dropped_tools", count=dropped) + nl

    if len(out) > max_chars:
        # 工具块全丢完还是超限：**保头保尾，从中间丢**。
        #
        # 不能直接 `out[:keep]`。开头有目标与约束，**结尾有当前进度**——
        # 而「上一个会话停在哪」正是交接最需要的一句。从头切等于把它扔掉，
        # 新会话于是不知道做到哪了。实测一个 3006 字符的会话被切到 2760 时，
        # 最后那条结论整条消失。
        #
        # 三分之一留给结尾：目标通常几段话就说完，而结尾的进度描述往往更长
        # （它要交代刚做完什么、下一步是什么）。
        full = len(out)
        note = nl + nl + "> " + tr.t("md.truncated", full=f"{full:,}", keep="") + nl
        room = max_chars - len(note) - 40
        if room < 400:
            # 上限小到连提示都放不下：只能截头部，但仍然说明截了。
            out = out[: max(0, max_chars - 40)] + nl + "> …" + nl
        else:
            tail = room // 3
            head_room = room - tail
            out = out[:head_room] + note + nl + out[-tail:]
    return out


__all__ = [
    "ASSISTANT_CHARS",
    "DEFAULT_MAX_CHARS",
    "TOOL_RESULT_CHARS",
    "USER_CHARS",
    "Turn",
    "deep_link",
    "is_boilerplate",
    "merge_tool_runs",
    "strip_thinking",
    "unwrap_injected",
    "portable_markdown",
    "read_claude_turns",
    "read_codex_turns",
    "read_turns",
    "render_markdown",
    "resume_command",
]
